language: node_js
node_js:
  - 10
dist: trusty
sudo: false
services:
  - docker

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run test
  - npm run build
  - echo instapy.io >> dist/CNAME
  - docker-compose build
deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy_docker.sh
    on:
      branch: master
  - deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist
    on:
      branch: master
